shell /usr/bin/fish
font_size 16.0
font_family JetBrainsMono Nerd Font Mono
window_padding_width 8
background_opacity 0.95
scrollback_lines 10000
copy_on_select clipboard
cursor_blink_interval 0.4 ease-in-out